fieldLayouts:
  57638220-e64e-4cdf-a987-c8d1b4a58a79:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cdc8afda-3f4c-44c0-b040-ba588a89d1c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f03b3c79-0597-4b66-b23b-519417ad4937 # First Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb0eae09-328e-4b12-a18c-56875ba55533
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74bd1a1d-cf8a-46c9-9d1c-50052ba6390d # First Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab184712-7b1f-4ed5-9d24-2da73c0f0498
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0dcb58ac-e0a1-4a13-a3a7-5ffdee433960 # First Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dc2a297-1be2-478f-a719-85ba446f1421
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70b81344-863b-459b-a6f0-16b1eced2112 # Second Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcb6c4c3-18c1-46bf-a18c-e5082046c67c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3da12c84-7583-44b0-8453-25d00c74aa4f # Second Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c234d29-403d-438e-aef5-f630907630f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8bae8270-1bfb-4ef1-90a5-6dbeb08afc90 # Third Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78f4a52a-0570-410a-954e-02b0b049eb68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4107459f-c1ee-491b-a01d-6fe56b00442c # Third Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 206c0dc3-da4b-4002-9c75-ce670919b28f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 133ac6e7-01dd-46ed-9db3-079ea8deb556 # Second Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29ddf47a-0b81-4cd6-aafd-faf37d52bb4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b816c57-aef9-4706-9306-f45991d7c7ec
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 4608749c-1ac8-41d2-a60c-20232d848674 # Home
sortOrder: 1
titleFormat: 'Electric Drill'
titleTranslationKeyFormat: null
titleTranslationMethod: site
