altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  31be3008-cda5-43ce-afa5-6a7d9319597a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-16T19:29:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 819732b1-2cf2-4faf-a380-874d742c1e32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 576ae2f6-5492-4536-8e34-d08eeff899f2
        userCondition: null
fs: glb
handle: glb
name: Glb
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
