columnSuffix: null
contentColumnType: string
fieldGroup: dd4ebc89-4e49-47dc-ab48-2233051c48e1 # Common
handle: glb3dFile
instructions: 'Add 3D GLB asset.'
name: 'GLB 3D File'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:0fd5a572-a9a7-4fef-9222-3b8be60e73f5' # Glb
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:0fd5a572-a9a7-4fef-9222-3b8be60e73f5' # Glb
  restrictedLocationSubpath: null
  selectionLabel: 'Add a 3D file'
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  sources:
    - 'volume:0fd5a572-a9a7-4fef-9222-3b8be60e73f5' # Glb
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
