columnSuffix: entjmzxp
contentColumnType: text
fieldGroup: dd4ebc89-4e49-47dc-ab48-2233051c48e1 # Common
handle: secondButton
instructions: 'Enter second button text'
name: 'Second Button'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Enter the second button text.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
