columnSuffix: vlcsnpdu
contentColumnType: text
fieldGroup: dd4ebc89-4e49-47dc-ab48-2233051c48e1 # Common
handle: secondHeading
instructions: 'Enter second heading text'
name: 'Second Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
