dateModified: 1742153659
email:
  fromEmail: sebastian.nadeau45@gmail.com
  fromName: drill-scroll
  transportType: craft\mail\transportadapters\Sendmail
fs:
  glb:
    hasUrls: true
    name: Glb
    settings:
      path: '@root/web/assets/glb'
    type: craft\fs\Local
    url: 'https://drill-scroll.ddev.site/assets/glb'
meta:
  __names__:
    06b282e2-fde0-44db-956f-65318238e98d: drill-scroll # drill-scroll
    7c9447ff-0044-4b0c-a5da-34c534673ae2: Simple # Simple
    12fdf15f-2302-4822-8522-57476ae57fb1: Home # Home
    56f81ca0-9d21-4a22-9f4a-ac0da6b48f2a: 'First Button' # First Button
    61cd3592-cd6f-4363-811d-696440c8ca30: 'Second Button' # Second Button
    171b7db2-f998-4f19-ab36-694927f87e51: 'Third Paragraph' # Third Paragraph
    189a459d-5125-41f4-9168-d6ad72c36f16: 'First Heading' # First Heading
    425a3203-c3d8-4997-9176-fe9e1b119abb: 'First Paragraph' # First Paragraph
    603683b7-a83c-4dff-a535-d8a6a1624ff2: 'Second Paragraph' # Second Paragraph
    d63b7918-9b9b-465e-9438-73ce1e29f44c: Home # Home
    e990f0c0-9fc1-431e-be46-5ca87155868a: 'Second Heading' # Second Heading
    e77847f5-6f8e-4b56-93da-fb4581582da5: 'Third Heading' # Third Heading
    f9ca987c-408c-431b-9952-2f1bb6913897: drill-scroll # drill-scroll
    fbfdbcb0-46bf-4f1f-856c-b8c178544c0d: 'GLB 3D File' # GLB 3D File
    ffd586d9-60ce-4209-8c12-2addae5f0931: Glb # Glb
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: drill-scroll
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
