defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  fff91f60-e98d-49d5-8484-d18086e7bb4c: # Drill Scroll
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
